version: '3'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ./wp-files
      o: bind
      type: none
  database:
    name: database
    driver: local
    driver_opts:
      device: ./db-files
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    ports:
      - '443:443'
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb
    env_file: .env
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    env_file: .env
    restart: on-failure
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    env_file: .env
    restart: on-failure
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    ports:
      - '1001:1001'
    networks:
      - inception
    depends_on:
      - mariadb
    env_file: .env
    restart: on-failure
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    networks:
      - inception
    env_file: .env
    restart: on-failure
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/.
    volumes:
      - wordpress:/var/www/html/
    ports:
      - '1002:21'
      - '30000-30009:30000-30009'
    networks:
      - inception
    env_file: .env
    restart: on-failure
  website:
    container_name: website
    build: ./requirements/bonus/website/.
    ports:
      - '8080:80'
    restart: on-failure
  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8090:8080"
    networks:
      - inception
    restart: on-failure
